integration:
  pob:
    connectTimeout: 10
    readTimeout: 20
    url: http://pob.url
logging:
  level:
    root: INFO
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.22:///
  flyway:
    enabled: true
