integration:
  pob:
    connectTimeout: 1
    readTimeout: 2
    url: http://localhost:${wiremock.server.port:}/pob
logging:
  level:
    root: INFO
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.22:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
